In [26]:
import torch
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler as ss
from sklearn.utils import shuffle

In [27]:
data = pd.read_csv("../iris.csv")
data = data.drop(["Id"], axis=1)

un_labels = data["Species"].unique()
# for i in data["Species"].unique():
#     print(sum(data["Species"]==i))

data = shuffle(data)
labels = data.pop("Species")
labels = np.array(labels)

data = ss().fit_transform(data)
print(un_labels)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [28]:
ohe_labels = np.zeros((len(labels), len(un_labels)))

for i in range(len(un_labels)):
    x = np.where(labels == un_labels[i])
    ohe_labels[x,i] = 1

ohe_labels[:10]

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
features = torch.tensor(np.array(data), dtype=torch.float32)
labels = torch.tensor(ohe_labels, dtype=torch.float32)

In [30]:
model = torch.nn.Sequential(
    torch.nn.Linear(4,4),
    torch.nn.ReLU(),
    torch.nn.Linear(4,3),
    torch.nn.Softmax(dim=-1)
)

preds = model(features)
print(preds[:5])

tensor([[0.2542, 0.4012, 0.3446],
        [0.2578, 0.3313, 0.4109],
        [0.2302, 0.4780, 0.2918],
        [0.2516, 0.4048, 0.3436],
        [0.2638, 0.3365, 0.3997]], grad_fn=<SliceBackward0>)


In [31]:
loss_fn = torch.nn.BCELoss()
opt = torch.optim.SGD(model.parameters(), lr = 1e-3)
loss = loss_fn(preds, labels)
print(loss)

tensor(0.6785, grad_fn=<BinaryCrossEntropyBackward0>)


In [32]:
# epochs = 1
# for epoch in range(epochs):

preds = model(features)

for i in range(len(preds)):
    pred_index = torch.where(preds[i]==preds[i].max())
    

(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([2]),)
(tensor([2]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([2]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1]),)
(tensor([1