In [1]:
import torch
from torch.nn.functional import mse_loss

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler

In [2]:

data = pd.read_csv("../life_expectancy.csv")
dataset = data.drop(["Country","Year"], axis=1).dropna()[:2000]
print(dataset.shape)


labels = dataset["Life"]

features = dataset.drop("Life",axis=1)
# print(features.info())

features = pd.get_dummies(features)


# print(features.info())
nplabels = np.array(labels).reshape(-1,1)
npfeatures = np.array(features)

npfeatures = StandardScaler().fit_transform(npfeatures)

features = torch.tensor(npfeatures, dtype = torch.float32)
labels = torch.tensor(nplabels,dtype = torch.float32)
# print(features.shape)


print(features[:5])

(1649, 20)
tensor([[ 0.7566,  0.2437, -1.1229, -0.3569, -0.5554, -0.1062, -0.9636,  0.2381,
         -3.4560,  0.9588, -0.8879, -0.3124, -0.4342,  0.2709,  2.6859,  2.6637,
         -0.8335, -0.7228, -0.4147,  0.4147],
        [ 0.8205,  0.2603, -1.1229, -0.3556, -0.6726, -0.1718, -0.9889,  0.2566,
         -1.1391,  0.9675, -1.0270, -0.3124, -0.4318, -0.2034,  2.7512,  2.7066,
         -0.8499, -0.7586, -0.4147,  0.4147],
        [ 0.7965,  0.2769, -1.1229, -0.3558, -0.5945, -0.1780, -1.0142,  0.2750,
         -0.9608,  0.9458, -0.9343, -0.3124, -0.4301,  0.2425,  2.7947,  2.7496,
         -0.8826, -0.7944, -0.4147,  0.4147],
        [ 0.8285,  0.3017, -1.1229, -0.3530, -0.4773,  0.0558, -1.0395,  0.2995,
         -0.7380,  1.1155, -0.7952, -0.3124, -0.4268, -0.1555,  2.8382,  2.8141,
         -0.9209, -0.8302, -0.4147,  0.4147],
        [ 0.8524,  0.3182, -1.1229, -0.3934, -0.4382,  0.0782, -1.0598,  0.3241,
         -0.6935,  0.8327, -0.7489, -0.3124, -0.4796, -0.1657,  2.9034,  2.8

In [3]:

model = torch.nn.Linear(20, 1)

print(model.weight)
print(model.bias)
preds=model(features)
print(preds)


Parameter containing:
tensor([[ 0.0492,  0.1206, -0.1647,  0.0469,  0.2122,  0.1007, -0.0068,  0.0553,
          0.0147, -0.1226, -0.1166, -0.0341,  0.0458,  0.0638,  0.0239, -0.0163,
          0.0504,  0.1226, -0.1750,  0.0815]], requires_grad=True)
Parameter containing:
tensor([0.2180], requires_grad=True)
tensor([[ 0.2839],
        [ 0.2735],
        [ 0.3088],
        ...,
        [-0.1744],
        [ 0.1961],
        [ 0.1675]], grad_fn=<AddmmBackward0>)


In [5]:

optimizer = torch.optim.SGD(model.parameters(), lr=1e-6)

epochs = 1000
for epoch in range(epochs):
    preds = model(features)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%100 == 0:
        print(epoch+1,loss)

    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()

# 5000 - 1500
# 10000 - 1350
# 50K - 1100

100 tensor(13.3120, grad_fn=<MseLossBackward0>)
200 tensor(13.3120, grad_fn=<MseLossBackward0>)
300 tensor(13.3120, grad_fn=<MseLossBackward0>)
400 tensor(13.3120, grad_fn=<MseLossBackward0>)
500 tensor(13.3120, grad_fn=<MseLossBackward0>)
600 tensor(13.3120, grad_fn=<MseLossBackward0>)
700 tensor(13.3120, grad_fn=<MseLossBackward0>)
800 tensor(13.3120, grad_fn=<MseLossBackward0>)
900 tensor(13.3120, grad_fn=<MseLossBackward0>)
1000 tensor(13.3120, grad_fn=<MseLossBackward0>)


In [13]:
index = 346

pred = model(features[index])

print(pred, labels[index])

tensor([77.5349], grad_fn=<AddBackward0>) tensor([78.9000])
