In [1]:
# auto grad modules
import torch

x = torch.tensor([1.0,2,3,4,5,6], requires_grad=True)
print(x)
y = x.sum()
print(y)
z = y*-2
print(z)

tensor([1., 2., 3., 4., 5., 6.], requires_grad=True)
tensor(21., grad_fn=<SumBackward0>)
tensor(-42., grad_fn=<MulBackward0>)


In [2]:
z.backward()

In [3]:
x.grad

tensor([-2., -2., -2., -2., -2., -2.])

In [4]:
import numpy as np
features = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]
], dtype=np.float64)

# labes Apples , Oranges
labels = np.array([
    [56, 70],
    [81, 101],
    [119, 133],
    [22, 37],
    [103, 119]
],dtype=np.float64)

In [5]:
features_tensor = torch.from_numpy(features)
features_tensor.requires_grad = True
print(features)

[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]


In [6]:
print(features_tensor)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]], dtype=torch.float64, requires_grad=True)
