In [1]:
import torch

In [2]:
# features Temp, Rainfall, Humidity
features = torch.tensor([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]
], dtype = torch.float32)

# labes Apples , Oranges
labels = torch.tensor([
    [56, 70],
    [81, 101],
    [119, 133],
    [22, 37],
    [103, 119]
], dtype = torch.float32)

In [3]:
# weights = torch.randn(2,3, requires_grad=True)
# bias = torch.randn(2, requires_grad=True)
# print(weights)
# print(bias)
model = torch.nn.Linear(3, 2)

print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.5758,  0.2485, -0.4836],
        [ 0.1999,  0.3102, -0.3253]], requires_grad=True)
Parameter containing:
tensor([ 0.3458, -0.0867], requires_grad=True)


In [4]:
preds = model(features)
print(preds)

tensor([[-45.8285,  21.3014],
        [-61.1282,  24.5825],
        [-44.4906,  40.0037],
        [-65.5909,  21.6054],
        [-49.3733,  20.7146]], grad_fn=<AddmmBackward0>)


In [5]:
# def mse(predictions , labels):
#     diff = predictions - labels
#     squared = diff**2
#     added = sum(sum(squared))
    
#     mean = added/(len(squared)*len(squared[0]))

#     return mean

from torch.nn.functional import mse_loss

loss  = mse_loss(preds, labels)
loss

tensor(11494.4971, grad_fn=<MseLossBackward0>)

In [21]:
loss.backward()

print(model.weight.grad)
print(model.bias.grad)

tensor([[ -9502.3750, -10522.6279,  -6506.8242],
        [ -4704.1909,  -5768.9961,  -3509.4121]])
tensor([-113.9948,  -58.2118])


In [22]:
# lr = 0.0000001

# with torch.no_grad():
#     model.weight -= lr*model.weight.grad
#     model.bias -= lr*model.bias.grad

optimizer = torch.optim.SGD(model.parameters(), lr=0.000001)

optimizer.step()
optimizer.zero_grad()

preds = model(features)
loss = mse_loss(preds, labels)
print(loss)

tensor(8686.0469, grad_fn=<MseLossBackward0>)


In [104]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.000001)

epochs = 10000
for epoch in range(epochs):
    preds = model(features)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%1000 == 0:
        print(loss)

    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()

tensor(0.5286, grad_fn=<MseLossBackward0>)
tensor(0.5268, grad_fn=<MseLossBackward0>)
tensor(0.5253, grad_fn=<MseLossBackward0>)
tensor(0.5241, grad_fn=<MseLossBackward0>)
tensor(0.5231, grad_fn=<MseLossBackward0>)
tensor(0.5222, grad_fn=<MseLossBackward0>)
tensor(0.5215, grad_fn=<MseLossBackward0>)
tensor(0.5209, grad_fn=<MseLossBackward0>)
tensor(0.5204, grad_fn=<MseLossBackward0>)
tensor(0.5200, grad_fn=<MseLossBackward0>)
