In [1]:
import numpy as np

In [2]:
# features Temp, Rainfall, Humidity
features = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]
])

# labes Apples , Oranges
labels = np.array([
    [56, 70],
    [81, 101],
    [119, 133],
    [22, 37],
    [103, 119]
])

label_1 = labels[:,0]
label_2 = labels[:,1]
print(label_1,label_2)

[ 56  81 119  22 103] [ 70 101 133  37 119]


In [3]:
weights = np.random.randn(3)
bias = np.random.randn()

print(weights, bias)

[ 0.96691194  1.50251736 -1.36447768] 0.39180017011751767


In [4]:
def predict(weights, bias):
    x = features*weights
    
    preds = np.zeros(len(features))
    for i in range(len(x)):
        preds[i] = np.sum(x[i])

    preds += bias

    return preds

preds = predict(weights, bias)

print(preds)

[112.97249438 133.2757425  206.71075924 113.13939013 115.83695261]


In [5]:
def mse(preds, labels):
    return np.sum((preds - labels)**2)/len(labels) # mean squared error
loss = mse(preds, label_1)
print(loss)

# loss.backward()
# w3.grad
# w1.grad
# w2.grad

4428.594288648541


In [6]:

diff = label_1 - preds

x1 = features[:, 0]
x2 = features[:, 1]
x3 = features[:, 2]

w1_grad = np.sum(-1 * diff * x1)/len(x1)
w2_grad = np.sum(-1 * diff * x2)/len(x1)
w3_grad = np.sum(-1 * diff * x3)/len(x1)

b_grad = np.sum(-1 * diff)/len(x1)

w_grad = np.array([w1_grad, w2_grad, w3_grad])
print(w_grad, b_grad)

[5345.77764703 5064.40108564 3030.68658641] 60.187067773582626


In [7]:
lr = 0.00001
weights = weights + (-1 * w_grad * lr)
bias = bias + (-1 * b_grad * lr)

print(weights, bias)

[ 0.91345416  1.45187335 -1.39478455] 0.39119829943978185


In [8]:
preds = predict(weights,bias)
loss = mse(preds, label_1)

print(loss)

3273.3905799427016


In [18]:
lr = 0.00001

for i in range(1000):
    diff = label_1 - preds

    x1 = features[:, 0]
    x2 = features[:, 1]
    x3 = features[:, 2]

    w1_grad = np.sum(-1 * diff * x1)/len(x1)
    w2_grad = np.sum(-1 * diff * x2)/len(x1)
    w3_grad = np.sum(-1 * diff * x3)/len(x1)

    b_grad = np.sum(-1 * diff)/len(x1)

    w_grad = np.array([w1_grad, w2_grad, w3_grad])
    # print(w_grad, b_grad)

    weights = weights + (-1 * w_grad * lr)
    bias = bias + (-1 * b_grad * lr)

    preds = predict(weights,bias)
    loss = mse(preds, label_1)

    print(loss)

0.9953367905395798
0.9953367352511965
0.9953366800556438
0.9953366249527636
0.995336569942381
0.9953365150243194
0.9953364601983928
0.9953364054644537
0.9953363508223234
0.9953362962718248
0.9953362418128062
0.9953361874450548
0.995336133168441
0.9953360789827675
0.995336024887888
0.9953359708836335
0.9953359169698025
0.9953358631462518
0.9953358094128119
0.995335755769321
0.9953357022155945
0.9953356487514554
0.9953355953767605
0.9953355420913524
0.9953354888950233
0.9953354357876438
0.995335382769041
0.9953353298390363
0.9953352769974655
0.9953352242441807
0.9953351715790066
0.9953351190017742
0.9953350665123141
0.9953350141104792
0.9953349617960849
0.9953349095690159
0.9953348574290508
0.9953348053760547
0.9953347534098563
0.9953347015303032
0.9953346497372367
0.995334598030486
0.9953345464098919
0.9953344948752882
0.9953344434265168
0.9953343920634327
0.9953343407858636
0.9953342895936469
0.9953342384866272
0.9953341874646503
0.9953341365275495
0.9953340856751742
0.9953340349073532

In [19]:
print(weights, bias)

[-0.40319114  0.84817322  0.6847279 ] 0.39305819737540887
