In [2]:
import numpy as np

In [32]:
x1 = np.array([1,2,5,6])

x2 = np.array([4,2,5,3])

x1 * x2

array([ 4,  4, 25, 18])

In [48]:
y1 = np.array([
    [2,4,6,8,10],
    [3,6,9,12,15]
])


y2 = np.array([
    [1,0,4,5,1]
])

y3 = np.array([
    [1],
    [2]
])

y1 + y2 , y1 + y3

(array([[ 3,  4, 10, 13, 11],
        [ 4,  6, 13, 17, 16]]),
 array([[ 3,  5,  7,  9, 11],
        [ 5,  8, 11, 14, 17]]))

In [3]:
z1 = np.array([
    [
        [2,1,5,3],
        [1,2,3,5],
        [9,5,0,3]
    ],
    [
        [2,-1,3,3],
        [1,5,3,2],
        [4,3,0,5]
    ]
])



z1.shape

(2, 3, 4)

In [47]:
# create a 3d array, then create all different possibly shaped arrays that can perform any operation with them