In [143]:
import numpy as np

In [144]:
o = np.array([
    [
        [2,1,5,3],
        [1,2,3,5],
        [9,5,0,3]
    ],
    [
        [2,-1,3,3],
        [1,5,3,2],
        [4,3,0,5]
    ]
])

In [145]:
x = np.random.random((3,5,4))

In [146]:
x = ((np.random.random((4,3,4))*200)-100)
x = np.array(x, dtype = int)

In [203]:
x = np.diag((3,2,4,1))
x

array([[3, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 1]])

In [204]:
np.flip(x, axis = 1)

array([[0, 0, 0, 3],
       [0, 0, 2, 0],
       [0, 4, 0, 0],
       [1, 0, 0, 0]])

In [205]:
np.flip(x, axis = 0)

array([[0, 0, 0, 1],
       [0, 0, 4, 0],
       [0, 2, 0, 0],
       [3, 0, 0, 0]])