In [2]:
import numpy as np

In [31]:
x = np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [37]:
x[x%2==0]

array([0, 2, 4])

In [6]:
x = np.random.randint(1,10, (2,5))
x

array([[8, 5, 2, 9, 4],
       [4, 8, 9, 2, 3]], dtype=int32)

In [7]:
x<=5

array([[False,  True,  True, False,  True],
       [ True, False, False,  True,  True]])

In [9]:
x[x<=5]

array([5, 2, 4, 4, 2, 3], dtype=int32)