In [1]:
import torch
import pandas as pd
import numpy as mp
from sklearn.preprocessing import StandardScaler as ss
from sklearn.utils import shuffle

In [2]:
data = pd.read_csv("../houses.csv").dropna()[:2500]
data = data.drop(["availability","location","society","total_sqft"], axis=1)
#print(data.shape)

print(data.info())


# bad dataset, biased, bad- values

label = data.pop("area_type")
data= pd.get_dummies(data)
print(data.head())


data = shuffle(data)

un_label = label.unique()
print(un_label)
oh_label = mp.zeros((len(label), len(un_label)))

for i in range(len(un_label)):
    x = mp.where(label == un_label[i])
    oh_label[x,i] = 1

print(oh_label)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2500 entries, 0 to 4513
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   area_type  2500 non-null   object 
 1   size       2500 non-null   object 
 2   bath       2500 non-null   float64
 3   balcony    2500 non-null   float64
 4   price      2500 non-null   float64
dtypes: float64(3), object(2)
memory usage: 117.2+ KB
None
    bath  balcony   price  size_1 BHK  size_1 RK  size_11 BHK  size_2 BHK  \
0    2.0      1.0   39.07           0          0            0           1   
1    5.0      3.0  120.00           0          0            0           0   
3    3.0      1.0   95.00           0          0            0           0   
5    2.0      1.0   38.00           0          0            0           1   
11   5.0      3.0  295.00           0          0            0           0   

    size_2 Bedroom  size_3 BHK  size_3 Bedroom  size_4 BHK  size_4 Bedroom  \
0             

In [ ]:
features = ss().fit_transform(data)

In [4]:
features = ss().fit_transform(data)

In [5]:
features = torch.tensor(features, dtype=torch.float32)
oh_labels = torch.tensor(oh_label, dtype=torch.float32)

In [6]:
print(features.shape, oh_label.shape)
print(features[:5])
print(oh_labels[:5])

torch.Size([2500, 17]) (2500, 4)
tensor([[ 0.6031, -0.8085,  0.1768, -0.2135, -0.0448, -0.0200, -0.9259, -0.0530,
          1.2319, -0.1291, -0.2216, -0.1581, -0.0400, -0.0400, -0.0283, -0.0200,
         -0.0200],
        [ 0.6031, -0.8085,  0.4669, -0.2135, -0.0448, -0.0200, -0.9259, -0.0530,
          1.2319, -0.1291, -0.2216, -0.1581, -0.0400, -0.0400, -0.0283, -0.0200,
         -0.0200],
        [-0.5146,  1.7356,  0.0801, -0.2135, -0.0448, -0.0200,  1.0800, -0.0530,
         -0.8117, -0.1291, -0.2216, -0.1581, -0.0400, -0.0400, -0.0283, -0.0200,
         -0.0200],
        [-0.5146, -0.8085, -0.3929, -0.2135, -0.0448, -0.0200,  1.0800, -0.0530,
         -0.8117, -0.1291, -0.2216, -0.1581, -0.0400, -0.0400, -0.0283, -0.0200,
         -0.0200],
        [ 0.6031,  1.7356,  1.0473, -0.2135, -0.0448, -0.0200, -0.9259, -0.0530,
          1.2319, -0.1291, -0.2216, -0.1581, -0.0400, -0.0400, -0.0283, -0.0200,
         -0.0200]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [

In [7]:
model = torch.nn.Sequential(
    torch.nn.Linear(17, 12),
    torch.nn.ReLU(),
    torch.nn.Linear(12, 4),
    torch.nn.Softmax(dim=-1)
)
loss_fn = torch.nn.BCELoss()

In [8]:
preds = model(features)
loss = loss_fn(preds, oh_labels)
preds

tensor([[0.3010, 0.2041, 0.2362, 0.2587],
        [0.2942, 0.2059, 0.2423, 0.2576],
        [0.2368, 0.2447, 0.2450, 0.2734],
        ...,
        [0.2673, 0.2230, 0.2395, 0.2702],
        [0.2667, 0.2236, 0.2406, 0.2691],
        [0.2724, 0.2270, 0.2653, 0.2354]], grad_fn=<SoftmaxBackward0>)