In [12]:
import torch
from torch.nn.functional import mse_loss
from torch.utils.data.dataloader import DataLoader

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler

In [13]:
data = pd.read_csv("../life_expectancy.csv")

train_dataset = data.drop(["Country","Year"], axis=1).dropna()[:1500]
test_dataset = data.drop(["Country","Year"], axis=1).dropna()[1500:]

In [20]:
train_labels = train_dataset["Life"]

train_features = train_dataset.drop("Life",axis=1)
# print(train_features.info())
train_features = pd.get_dummies(train_features)


# print(train_features.info())
nptrain_labels = np.array(train_labels).reshape(-1,1)
nptrain_features = np.array(train_features)

nptrain_features = StandardScaler().fit_transform(nptrain_features)

train_features = torch.tensor(nptrain_features, dtype = torch.float32)
train_labels = torch.tensor(nptrain_labels,dtype = torch.float32)
# print(train_features.shape)

train_loader = DataLoader(train_features, batch_size= 100)

for i in train_loader:
    print(i.shape)
# print(train_features[:5])

torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])


In [16]:
model = torch.nn.Linear(20, 1)

print(model.weight)
print(model.bias)
preds=model(train_features)
print(preds)

Parameter containing:
tensor([[ 0.0501, -0.1472,  0.1028,  0.0888, -0.1627, -0.0938, -0.2112, -0.0226,
          0.0107,  0.1540, -0.0023,  0.1848,  0.1181, -0.1315,  0.1420, -0.0314,
          0.0326, -0.1462,  0.1054,  0.0921]], requires_grad=True)
Parameter containing:
tensor([0.1692], requires_grad=True)
tensor([[0.6527],
        [0.7826],
        [0.7229],
        ...,
        [0.2939],
        [0.0614],
        [0.3025]], grad_fn=<AddmmBackward0>)


In [18]:

optimizer = torch.optim.SGD(model.parameters(), lr=1e-6)

epochs = 1000
for epoch in range(epochs):
    preds = model(train_features)
    loss = mse_loss(preds, train_labels)
    
    if (epoch+1)%100 == 0:
        print(epoch+1,loss)

    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()

# 5000 - 1500
# 10000 - 1350
# 50K - 1100

100 tensor(4891.7505, grad_fn=<MseLossBackward0>)
200 tensor(4889.6997, grad_fn=<MseLossBackward0>)
300 tensor(4887.6499, grad_fn=<MseLossBackward0>)
400 tensor(4885.6016, grad_fn=<MseLossBackward0>)
500 tensor(4883.5532, grad_fn=<MseLossBackward0>)
600 tensor(4881.5063, grad_fn=<MseLossBackward0>)
700 tensor(4879.4604, grad_fn=<MseLossBackward0>)
800 tensor(4877.4165, grad_fn=<MseLossBackward0>)
900 tensor(4875.3726, grad_fn=<MseLossBackward0>)
1000 tensor(4873.3306, grad_fn=<MseLossBackward0>)


In [ ]:
index = 346

pred = model(features[index])

print(pred, labels[index])

tensor([77.5349], grad_fn=<AddBackward0>) tensor([78.9000])
