In [20]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.losses import MSE

print(tf.__version__)
# why tensors if numpy works, just as fast?
# less code, gpu, autograd

2.10.0


In [21]:
# scalar
x = tf.constant(3.14)
x

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [22]:
# vector
x = tf.constant( [[2,3,5], [1,9,4]] ) #dtype can be used
# x[0][2] = 3
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 5],
       [1, 9, 4]])>

In [23]:
x = tf.Variable(4)
x.assign(3)
x.assign_add(1)
x.assign_sub(2)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

In [24]:
x = tf.Variable([[2,3,5], [1,9,4]])
x[0,2].assign(3)
x

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 3],
       [1, 9, 4]])>

In [25]:
x = np.arange(1,25).reshape(3,2,4)

x = tf.Variable(x)
print(x)

<tf.Variable 'Variable:0' shape=(3, 2, 4) dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])>


In [26]:
x = tf.random.uniform(shape=(3,2))  #uniform, zeros,ones
x

x = tf.zeros(shape=(2,4,3))
x

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [27]:
x = tf.Variable([[1,2], [3,4], [5,6], [7,8]])
x = tf.random.shuffle(x)
print(x * 10)
print(tf.math.multiply(x,10))

tf.Tensor(
[[70 80]
 [10 20]
 [30 40]
 [50 60]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[70 80]
 [10 20]
 [30 40]
 [50 60]], shape=(4, 2), dtype=int32)


In [28]:
x = tf.constant(np.arange(1,13).reshape(3,4))
y = tf.constant(np.arange(1,9).reshape(2,4))

print(x)
# y = tf.reshape(y,shape=(4,2))
y = tf.transpose(y) 

# print(x)
print(y)

# Dot product
print(x @ y)
# print(tf.matmul(x,y))
# print(tf.tensordot(x,y, axes=1))

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 5]
 [2 6]
 [3 7]
 [4 8]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[ 30  70]
 [ 70 174]
 [110 278]], shape=(3, 2), dtype=int32)


In [29]:
x = tf.random.normal(shape=(3,3))
print(x)

tf.Tensor(
[[-2.2677305  -0.04812891  0.69278216]
 [ 0.39355507 -1.262451    0.03362634]
 [ 0.42073312  2.6847463  -1.2093436 ]], shape=(3, 3), dtype=float32)


In [30]:
x = tf.cast(x, dtype=tf.int16)
x

<tf.Tensor: shape=(3, 3), dtype=int16, numpy=
array([[-2,  0,  0],
       [ 0, -1,  0],
       [ 0,  2, -1]], dtype=int16)>

In [31]:
tf.abs(x)

<tf.Tensor: shape=(3, 3), dtype=int16, numpy=
array([[2, 0, 0],
       [0, 1, 0],
       [0, 2, 1]], dtype=int16)>

In [32]:
print(tf.reduce_min(x))
print(tf.reduce_max(x))
print(tf.reduce_mean(x))
print(tf.reduce_sum(x))

tf.Tensor(-2, shape=(), dtype=int16)
tf.Tensor(2, shape=(), dtype=int16)
tf.Tensor(0, shape=(), dtype=int16)
tf.Tensor(-2, shape=(), dtype=int16)


In [43]:
x = tf.constant(np.arange(1,13).reshape(3,4))
tf.keras.utils.normalize(x, axis=1)

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[0.2       , 0.4       , 0.6       , 0.8       ],
       [0.38461538, 0.46153846, 0.53846154, 0.61538462],
       [0.42857143, 0.47619048, 0.52380952, 0.57142857]])>

In [47]:
x = tf.ones(shape=(1,2,1,1,3))
x = tf.squeeze(x)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>