In [1]:
import tensorflow as tf
from tensorflow.keras.losses import MSE
from tensorflow.keras import layers
import pandas as pd

In [2]:
data = pd.read_csv("./data/weather.csv")[:90000]
data.head(2)

Formatted Date        Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.

In [3]:
features = data[["Temperature (C)","Humidity","Wind Speed (km/h)","Pressure (millibars)","Wind Bearing (degrees)","Summary"]]
features = pd.get_dummies(features)
mean = features.mean()
std = features.std()
features = (features - mean)/ std
labels = data[["Apparent Temperature (C)","Visibility (km)"]]

features = tf.cast(tf.constant(features), dtype=tf.float32)
labels = tf.cast(tf.constant(labels), dtype=tf.float32)

In [4]:
model = tf.keras.Sequential([
    layers.Dense(5),
    layers.Activation("relu"),
    layers.Dense(2)
])

In [5]:
model.build(input_shape=(90000,31))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (90000, 5)                160       
                                                                 
 activation (Activation)     (90000, 5)                0         
                                                                 
 dense_1 (Dense)             (90000, 2)                12        
                                                                 
Total params: 172
Trainable params: 172
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.compile(
    optimizer = tf.keras.optimizers.Adam(),
    loss = "mse"
)

In [14]:
model.fit(
    features,
    labels,
    epochs = 100,
    batch_size = 90
)

Epoch 1/100
1000/1000 [==============================] - 1s 645us/step - loss: 4.2279
Epoch 2/100
1000/1000 [==============================] - 1s 655us/step - loss: 4.2177
Epoch 3/100
1000/1000 [==============================] - 1s 664us/step - loss: 4.2177
Epoch 4/100
1000/1000 [==============================] - 1s 654us/step - loss: 4.2153
Epoch 5/100
1000/1000 [==============================] - 1s 650us/step - loss: 4.2173
Epoch 6/100
1000/1000 [==============================] - 1s 669us/step - loss: 4.2138
Epoch 7/100
1000/1000 [==============================] - 1s 681us/step - loss: 4.2135
Epoch 8/100
1000/1000 [==============================] - 1s 703us/step - loss: 4.2129
Epoch 9/100
1000/1000 [==============================] - 1s 673us/step - loss: 4.2128
Epoch 10/100
1000/1000 [==============================] - 1s 668us/step - loss: 4.2110
Epoch 11/100
1000/1000 [==============================] - 1s 655us/step - loss: 4.2126
Epoch 12/100
1000/1000 [============================

In [12]:
model.predict(
    features[10000:10010]
)

1/1 [==============================] - 0s 17ms/step


array([[25.392513, 11.774443],
       [26.518696, 11.796934],
       [26.880013, 11.989243],
       [26.902248, 11.969256],
       [24.315737, 12.031952],
       [21.969828,  8.074538],
       [22.758602, 11.844312],
       [21.7036  , 11.812504],
       [20.169083, 11.817416],
       [18.097565,  8.102919]], dtype=float32)

In [13]:
labels[10000:10010]

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[25.166666, 15.8263  ],
       [26.455555, 15.5204  ],
       [27.422222, 15.7136  ],
       [27.283333, 15.8263  ],
       [24.4     , 14.9569  ],
       [22.7     ,  9.982   ],
       [22.594444, 15.8263  ],
       [21.566668, 14.329   ],
       [20.13889 , 11.5437  ],
       [18.88889 ,  9.982   ]], dtype=float32)>