In [5]:
import pandas as pd
from matplotlib import pyplot as plt 
import numpy as np
import torch
from sklearn.preprocessing import StandardScaler

In [6]:
dataset=pd.read_csv("./life_expectancy.csv")
#dataset=dataset.dropna(axis=0)

dataset=dataset.drop(["Country","Year"],axis=1).dropna()[:500]
print(dataset.columns)
label=dataset["Life"]
label1=np.array(label).reshape(-1,1)
labels=torch.tensor(label1,dtype=torch.float32)
fea=dataset.drop("Life",axis=1)
fea1=pd.get_dummies(fea)
fea2=np.array(fea1)
fea3= StandardScaler().fit_transform(fea2)
features=torch.tensor(fea3,dtype=torch.float32)
print(features)
print(labels)

Index(['Status', 'Life', 'Adult Mortality', 'infant deaths', 'Alcohol',
       'percentage expenditure', 'Hepatitis B', 'Measles ', ' BMI ',
       'under-five deaths ', 'Polio', 'Total expenditure', 'Diphtheria ',
       ' HIV/AIDS', 'GDP', 'Population', ' thinness  1-19 years',
       ' thinness 5-9 years', 'Income composition of resources', 'Schooling'],
      dtype='object')
tensor([[ 0.8424,  0.6216, -1.2282,  ..., -0.6414, -0.4429,  0.4429],
        [ 0.9085,  0.6550, -1.2282,  ..., -0.6725, -0.4429,  0.4429],
        [ 0.8837,  0.6884, -1.2282,  ..., -0.7036, -0.4429,  0.4429],
        ...,
        [-0.0424, -0.4132,  2.3828,  ...,  1.2270, -0.4429,  0.4429],
        [ 0.0486, -0.4132,  2.8512,  ...,  1.2270, -0.4429,  0.4429],
        [ 0.2305, -0.4132,  3.0627,  ...,  1.2270, -0.4429,  0.4429]])
tensor([[65.0000],
        [59.9000],
        [59.9000],
        [59.5000],
        [59.2000],
        [58.8000],
        [58.6000],
        [58.1000],
        [57.5000],
        [57.3

In [12]:
model=torch.nn.Sequential(
torch.nn.Linear(20,10),
torch.nn.ReLU(),
torch.nn.Linear(10,1)
)

for i in model.parameters():
    print(i)


Parameter containing:
tensor([[ 0.1780,  0.1781, -0.2206,  0.0921,  0.1572, -0.1812, -0.1129,  0.1004,
          0.1046, -0.0348,  0.0586, -0.1034,  0.2056,  0.0253,  0.1848,  0.1963,
          0.2230,  0.0237, -0.0032,  0.0535],
        [ 0.0406, -0.1465, -0.1205, -0.2198, -0.0571,  0.0598,  0.0397, -0.0509,
          0.1569,  0.1246,  0.0995, -0.0652, -0.1965, -0.1324, -0.0790, -0.0541,
          0.1643,  0.1734,  0.0073, -0.0230],
        [ 0.1478, -0.1860, -0.0214,  0.0393,  0.0989,  0.2006, -0.2124,  0.1088,
         -0.1689,  0.1815,  0.0317,  0.0599, -0.1711, -0.1052, -0.1402, -0.0126,
          0.1222,  0.1573, -0.1470,  0.0130],
        [-0.0470,  0.0262, -0.1192,  0.0017, -0.0701,  0.0864,  0.2069, -0.0207,
         -0.1274, -0.0947, -0.0023,  0.1651, -0.2025, -0.1021, -0.0776,  0.1584,
         -0.2171, -0.0949, -0.1116, -0.0943],
        [ 0.0924,  0.0052, -0.2197,  0.1973, -0.2210,  0.1110,  0.2117,  0.0785,
          0.1739,  0.0563,  0.1564, -0.2026, -0.0567,  0.0804,  0

In [14]:
preds=model(features)
print(preds[:5])

tensor([[-0.4127],
        [-0.3685],
        [-0.4198],
        [-0.3813],
        [-0.3460]], grad_fn=<SliceBackward0>)


In [15]:
from torch.nn.functional import mse_loss
loss=mse_loss(preds,labels)
print(loss)

tensor(5038.4932, grad_fn=<MseLossBackward0>)


In [15]:
loss.backward()


In [16]:
optimizer=torch.optim.SGD(model.parameters(),lr=1e-12)
optimizer.step()
preds=model(features)
loss=mse_loss(preds,labels)
print(loss)

tensor(5038.4932, grad_fn=<MseLossBackward0>)


In [25]:
optimizer=torch.optim.SGD(model.parameters(),lr=1e-3)
epochs=10000
for epoch in range(epochs):
    preds=model(features)
    loss=mse_loss(preds,labels)
    if(epoch+1)%1000==0:
        print(loss)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

tensor(1.7051, grad_fn=<MseLossBackward0>)
tensor(1.6955, grad_fn=<MseLossBackward0>)
tensor(1.6889, grad_fn=<MseLossBackward0>)
tensor(1.6834, grad_fn=<MseLossBackward0>)
tensor(1.6763, grad_fn=<MseLossBackward0>)
tensor(1.6704, grad_fn=<MseLossBackward0>)
tensor(1.6653, grad_fn=<MseLossBackward0>)
tensor(1.6599, grad_fn=<MseLossBackward0>)
tensor(1.6551, grad_fn=<MseLossBackward0>)
tensor(1.6502, grad_fn=<MseLossBackward0>)


In [24]:
i = 101

f = features[i]
pred = model(f)
print(pred, labels[i])

tensor([79.6173], grad_fn=<AddBackward0>) tensor([79.8000])
